preload = /home/rcamara/Repos/wpaper/wallpaper.png
wallpaper = DP-2,/home/rcamara/Repos/wpaper/wallpaper.png
wallpaper = HDMI-A-1,/home/rcamara/Repos/wpaper/wallpaper.png
wallpaper = eDP-1,/home/rcamara/Repos/wpaper/wallpaper.png
splash = false
ipc = true
